### ISSUE TITLE
Not working Clicked and drop?

### ISSUE THREAD

**Issue by KGPARMAR** [oakmac/chessboardjs#175]
I have play this example but here only working drag and drop but not working,
see example: https://play.google.com/store/apps/details?id=org.petero.droidfish
move like this

**Comment by theostavrides** [comment]
It would be really great if this was implemented.  I see that someone made a pull request to integrate click moves but it wasn't working for me.

**Comment by vesper8** [comment]
I forked the project and made click-and-drop work with 1.0 using as inspiration this PR: https://github.com/oakmac/chessboardjs/pull/138 by @pino

It works really well and the modification was very simple. I want to create a PR but because this file https://github.com/oakmac/chessboardjs/blob/master/lib/chessboard.js has a "mixed line endings issue", I cannot create a PR without causing the entire file to become one big diff. I reported this to Github so we'll see what they say.

Anyway here are the modifications.. very simple stuff

replace
```
    var squareSize = 16
```

by
```
    var squareSize = 16
    var clickMove = false
```

replace
```
    function dropDraggedPieceOnSquare (square) {

      removeSquareHighlights()
```

by
```
    function dropDraggedPieceOnSquare (square) {

      // if destination is same as source, piece stays picked up and is dropped at the next clicked square.
      if (clickMove == false) {
        if (square === draggedPieceSource) {
          clickMove = true;
          return;
        }
      }

      clickMove = false;

      removeSquareHighlights()
```

replace
```
    function stopDraggedPiece (location) {
      // determine what the action should be
      var action = 'drop'

      if (location === 'offboard' && config.dropOffBoard === 'snapback') {
        action = 'snapback'
      }
```

by
```
    function stopDraggedPiece (location) {
      // determine what the action should be
      var action = 'drop'

      if (location === 'offboard' && config.dropOffBoard === 'snapback') {
        action = 'snapback'
        clickMove = false;
      } else {
        if (clickMove == false) {
          // pick up spare piece and put it down on next clicked square
          clickMove = true;
          return;
        } else {
          // drop piece back on its origin square
          clickMove = false;
        }
      }
```

and voila.. that's it.. works perfectly for me on 1.0

Just download the zip from the website and apply these modifications to the non-minified version

**Comment by larskuerten** [comment]
I follow the instructions, it works to move but not capturing.

**Comment by KGPARMAR** [comment]
Thanks brother it's working find!
