### ISSUE TITLE
How to choose pawn promotion?

### ISSUE THREAD

**Issue by happyByNature** [oakmac/chessboardjs#43]
It there are option to be able to choose to what promote the pawn?

**Comment by manuelc65** [comment]
hola Como puedo enfrentar dos motores de ajedrez con chessboard.js
engine vs engine  o komodo.js vs stockfish.js
``` Javascript
var board, 
game = new Chess();
 var makeRandomMove = function() { 
  var possibleMoves = game.moves();
 
 // exit if the game is over
 if (game.game_over() === true || 
    game.in_draw() === true ||
     possibleMoves.length === 0)
 return;
 //var randomIndex = Math.floor(Math.random() * possibleMoves.length);
//engine player1
var engine =Worker ("stockfish.js");
engine.onmessage = handle_message;
 
 game.move(possibleMoves[randomIndex]);
 board.position(game.fen());
 //window.setTimeout(makeRandomMove, 500); };
 
//engineplayer2
 board = new ChessBoard('board', 'start');
 var engine2 =Worker ("komodo.js");    
 engine.onmessage = handle_message;
 
 //window.setTimeout(makeRandomMove, 500);
```
examples#5002 
Como puedo hacer esto este ejemplo RND vs RND pero lo que yo quiero hacer es 
ENGINE2 vs ENGINE2 gracias por la ayuda

**Comment by oakmac** [comment]
Hi :)

I don't speak spanish, but I believe this should be opened as a separate [GitHub issue](https://github.com/oakmac/chessboardjs/issues/new).

Thanks,
Chris
----------[ GOOGLE TRANSLATE ]----------
Hola :)

Yo no hablo español, pero creo que esto se debe abrir como un tema aparte GitHub.

Gracias,
Chris

**Comment by manuelc65** [comment]
Gracias por responder es que es una pregunta que quería que tu me la respondieras por que yo no se como hacerlo he visto tu código de chessboardjs y un no he podido solucionarlo
 esta es un pregunta dirigida a usted que es el desarrollador creí que podías ayudarme Gracias
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
y la pregunta es como puedo hacer que dos motores de ajedrez se enfrente usando tu código
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
----------[ GOOGLE TRANSLATE ]----------
Please answer is that it is a question that wanted you respondieras me because I do not know how I saw your code chessboardjs and I could not fix it
  this is a question to you which is the developer thought it could help me Thanks
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
and the question is how can I do that two opposite chess engines using your code
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

gracias por tu ayuda

thanks for your help

**Comment by user14159** [comment]
No solution yet fhinson?

**Comment by manuelc65** [comment]
Ya solucione con un pequeño script para que el jugador pueda coronar y seleccionar la pieza que desee
al coronar 

And solved with a small script so that the player may promotion and select the part you want
the Crown

https://github.com/manuelc65/Promotion-chess.js-chessboard.js

**Comment by user14159** [comment]
Does seem to look good. The only problem being the pawn bounces back to it's pre-promotion square before the promotion piece is selected. An unwanted result of the drawPositionInstant() function?

**Comment by manuelc65** [comment]
Si tiene razón fue la única opción que logre para hacer eso sin hacerle modificaciones ala las do api chess.js y stockfish.js  pero creo que puedo hacer que el peón se oculte o no se vea mientras se toma la opción del peón también creo que se pude lograr poner la mini popu que tape esta opción al el peón retroceder 
translate google
If you have reason was the only option that achieves to do that without making the api wing modifications do chess.js and stockfish.js but I think I can make the pawn hide or display while option takes pawn I also believe that I could achieve was to put the popu mini tape this option when the pawn back

**Comment by user14159** [comment]
It might be related to this other problem. As you seem very well versed in javascript, any ideas on this one?

https://github.com/oakmac/chessboardjs/pull/42
