### ISSUE TITLE
When setting position option, Engine is not recognizing it

### ISSUE THREAD

**Issue by khinklenj** [oakmac/chessboardjs#65]
I am having an issues when I set the position to "pp3k2/8/8/8/8/8/8/RNBQKBNR" it seams the engine is not recognizing it. I am using Chess.js.

The board is coming up correctly, I can not move any piece except either white Knight but when I do the board resets back to default.

**Comment by nickborti** [comment]
@oakmac I'm facing similar problem like @khinklenj . If I save the fen of a particular chessboard which is actually dumb, and I want to load that fen and make the game playable from that position, what should I do?

It has something to do with converting `chessboardjs FEN` to `chessjs FEN`. How will I convert this to make the game playable?

**Comment by oakmac** [comment]
The [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) code that chessboard.js understands is not a "true FEN" since it does not contain information about the state of the game: how many moves have been played, who's turn it is, en passant available, etc.

chessboard.js only understands the first part of a FEN string: information about the pieces on the board.

The chess.js library understands the full FEN code since each game object holds the full state of the game.

In order to convert between the two should just be some basic string manipulation. Appending the game state information to the end of the board information.

**Comment by nickborti** [comment]
@oakmac I understand. But what if I manually create a board with random pieces from outside the board? In this case, since there isn't any game played yet (will be played later), from where is it possible to get the game-state string which can be appended to the board FEN? I hope you understand my concern here.
