### ISSUE TITLE
Move notation chessjs and chessboardjs

### ISSUE THREAD

**Issue by AndyPi** [oakmac/chessboardjs#92]
I am trying a rough and ready integration of stockfish with chessboardjs.  I am using example 5001 as start point.  I notice that chessjs uses standard algebraic while chessboardjs and stockfish use long.  Is there a utility available for conversion?

**Comment by oakmac** [comment]
chessboard.js cannot support [Algebraic notation](https://en.wikipedia.org/wiki/Algebraic_notation_(chess)) because it doesn't have knowledge of the game (ie: who's move it is, whether en passant is possible, etc).

This logic is better left to the [chess.js](https://github.com/jhlywa/chess.js) library, and I believe it's API supports multiple forms of notation.
