### ISSUE TITLE
To append captured images to separate div

### ISSUE THREAD

**Issue by tgoldenberg** [oakmac/chessboardjs#99]
I looked through the source js code and was unable to find the function that fadesOut or remove()s the captured pieces. If I can find that code, then I can change it from fadeOut() or remove() to detach().appendTo('my-div') to show captured pieces. Any suggestion?

**Comment by tgoldenberg** [comment]
I created a new issue because this is different from the solved issue of draggable elements

**Comment by oakmac** [comment]
chessboard.js doesn't know about "capturing pieces" because it has no knowledge of the game logic behind chess (this is intentional, and usually handled separately by integrating with the [chess.js](https://github.com/jhlywa/chess.js) library).

chessboard.js only knows about positions. A move that captures a piece just represents a new position for chessboard.js. Any logic behind piece capturing, which piece was captured, what to do with the piece when it's captured, etc should happen outside the chessboard.js code.
